In [ ]:
import numpy as np

In [ ]:
# 넘파이, 판다스 정도만 () 안씁니다.. shape.. ndim.. <- property
l1 = [1,2,3]
array1 = np.array(l1)
print('array1의 type:', type(array1))
print('array1의 shape:', array1.shape)
print('array1의 차원은 {0}차원 입니다'.format(array1.ndim))

array1의 type: <class 'numpy.ndarray'>
array1의 shape: (3,)
array1의 차원은 1차원 입니다


In [ ]:
l2 = [[1,3,5],
      [2,4,6]]
array2 = np.array(l2)
print('array2의 type:', type(array2))
print('array2의 shape:', array2.shape)
print('array2의 차원은 {0}차원 입니다'.format(array2.ndim))

array2의 type: <class 'numpy.ndarray'>
array2의 shape: (2, 3)
array2의 차원은 2차원 입니다


In [ ]:
# (1, 4, 1) 해당하는 shape을 만들어보세요.
l4 = [ [[1], [2], [3], [4] ] ]
my_array = np.array(l4)
print(my_array.shape)

(1, 4, 1)


### ndarray를 편리하게 생성

In [ ]:
### arange 함수
sq_array = np.arange(1, 11)
print(sq_array)
print(sq_array.dtype, sq_array.shape)
print()

### zeros 함수
z_array = np.zeros((3,2), dtype='int64')
print(z_array)
print(z_array.dtype, z_array.shape)
print()

### ones 함수
o_array = np.ones((2,3), dtype='int64')
print(o_array)
print(o_array.dtype, o_array.shape)
print()

### reshape
array_1d = np.arange(1, 11)
array_2d = array_1d.reshape(2, 5) # 사이즈 안맞으면 에러 # array_1d.reshape(-1, 5) 가능
array_3d = np.arange(1,9).reshape(2,2,2)
array_2d

[ 1  2  3  4  5  6  7  8  9 10]
int64 (10,)

[[0 0]
 [0 0]
 [0 0]]
int64 (3, 2)

[[1 1 1]
 [1 1 1]]
int64 (2, 3)



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 인덱싱 및 슬라이싱

1. 특정 데이터 추출
2. 슬라이싱(Slicing)
3. 팬시 인덱싱(Fancy Idx)
4. 불리언 인덱싱(Boolean Idx)

In [ ]:
array1 = np.arange(start=1, stop=10)
print('value:', array1[2])
print('value의 타입:', type(array1[2]))

value: 3
value의 타입: <class 'numpy.int64'>


In [ ]:
array2 = array1.copy()
array_2d = array2.reshape(3, 3)
print('(row=0, col=0) idx 가리키는 값:', array_2d[0,0])
print('(row=0, col=1) idx 가리키는 값:', array_2d[0,1])
print('(row=1, col=0) idx 가리키는 값:', array_2d[1,0])
print('(row=2, col=2) idx 가리키는 값:', array_2d[2,2])

(row=0, col=0) idx 가리키는 값: 1
(row=0, col=1) idx 가리키는 값: 2
(row=1, col=0) idx 가리키는 값: 4
(row=2, col=2) idx 가리키는 값: 9


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print(array2d)

print('array2d:\n',array2d[0:2,0:2])
print('array2d:\n',array2d[1:3,0:3])
print('array2d:\n',array2d[1:3,:])
print('array2d:\n',array2d[:,:])
print('array2d:\n',array2d[:2,1:])
print('array2d:\n',array2d[:2,0]) # 0: 슬라이싱x, 지칭 -> 결과가 1차원으로 나타남
print('array2d:\n',array2d[:2,0:1])
print('array2d:\n',array2d[0,:2])
# [행 슬라이싱, 열 슬라이싱]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d:
 [[1 2]
 [4 5]]
array2d:
 [[4 5 6]
 [7 8 9]]
array2d:
 [[4 5 6]
 [7 8 9]]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d:
 [[2 3]
 [5 6]]
array2d:
 [1 4]
array2d:
 [[1]
 [4]]
array2d:
 [1 2]
